src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/orders/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('', views.ListOrder.as_view(), name='list'),
    path('user', views.MyOrder.as_view(), name='user'),
    path('<int:pk>/create', views.CreateOrder.as_view(), name='create'),
    path('<int:pk>/detail', views.ShowOrder.as_view(), name='detail'),
    path('<int:pk>/delete', views.DeleteOrder.as_view(), name='delete'),
    path('<int:pk>/append', views.AddCustomer.as_view(), name='append'),
    path('<int:pk>/drop/<int:ck>', views.DropCustomer.as_view(), name='drop'),
    path('<int:pk>/update/<int:ck>', views.ChangeCustomer.as_view(), name='update'),
    path('<int:pk>/status/<str:status>', views.ChangeOrderStatus.as_view(), name='status'),
]

src/users/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('update/', views.ChangeUser.as_view(), name='change'),
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>
        {% block title %}
        EcCoSy
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
<script>
    $('#searchGo').click(function () {
        const searchWord = document.getElementById("searchWord").value;
        if (searchWord != "") {
            console.log(searchWord);
            $(".searchInMe").each(function (i, el) {
                console.log(i);
                console.log(el);
                el.contains(searchWord)
                console.log("нашел - " el);
            })
        }
    })
</script>
</body>
</html>

src/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="vertical">
        <div class="container">
            <div class="center">
                <div class="banner h1 mb-5">Buy together, get profit. <br>
                    <small class="accent">EcCoSy</small>
                </div>
                {% if user.is_authenticated %}
                    <div class="mt-5 pt-5">
                        <h2>Welcome, {{ user.username }}.</h2>
                        <a class="btn btn-info" href="{% url 'order:list' %}">MAIN</a>
                        <a class="btn btn-info" href="{% url 'user:change' %}">PROFILE</a>
                        <a class="btn btn-info" href="{% url 'order:user' %}">MY ORDERS</a>
                        <br>
                        <a class="btn btn-outline-secondary mt-4" href="{% url 'logout' %}">LOG OUT</a>
                        {% else %}
<!--                        <p>You are not logged</p>-->
                         <a class="btn btn-info" href="{% url 'login' %}">LOG IN</a>
                         <a class="btn btn-info" href="{% url 'user:signup' %}">SIGN UP</a> <br>
                         <a class="btn btn-outline-secondary mt-4" href="admin">ADMIN IN</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}