src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/orders/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('', views.ListOrder.as_view(), name='list'),
    path('user', views.MyOrder.as_view(), name='user'),
    path('<int:pk>/create', views.CreateOrder.as_view(), name='create'),
    path('<int:pk>/detail', views.ShowOrder.as_view(), name='detail'),
    path('<int:pk>/delete', views.DeleteOrder.as_view(), name='delete'),
    path('<int:pk>/append', views.AddCustomer.as_view(), name='append'),
    path('<int:pk>/drop/<int:ck>', views.DropCustomer.as_view(), name='drop'),
    path('<int:pk>/update/<int:ck>', views.ChangeCustomer.as_view(), name='update'),
    path('<int:pk>/status/<str:status>', views.ChangeOrderStatus.as_view(), name='status'),
]

src/users/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('update/', views.ChangeUser.as_view(), name='change'),
]

src/orders/models.py
from django.db import models
from django.contrib.auth import get_user_model

from .managers import CustomerManager, DiscountsManager, OrderManager


User = get_user_model()


class Order(models.Model):
    STATUS = (('WORK', 'WORK'),
              ('START', 'START'),
              ('FINISH', 'FINISH'),
              ('ARCHIVE', 'ARCHIVE'))
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=256, choices=STATUS, null=False, default='START'
    )
    date_start = models.DateTimeField(auto_now_add=True)
    date_finish = models.DateTimeField(blank=True)
    # address = models.CharField(max_length=256)
    comment = models.TextField(default='')

    objects = OrderManager()

    def __str__(self):
        return f'<{self.creator}>{self.product}'

    @property
    def customers(self):
        customers = list(self.customer_set.values_list('user', flat=True))
        cust_vals = list(self.customer_set.values_list('user', 'size'))
        sizes = list(self.customer_set.values_list('size', flat=True))
        size = sum(sizes)

        percent = self.product.discounts.discounts.get_percent(size)
        price = self.product.pph - (self.product.pph / 100) * percent
        self.product.discounts.discounts.get_all_percent()
        usernames = list(User.objects.filter(pk__in=customers).values_list('username', flat=True))
        out = zip(usernames, sizes, map(lambda x: "{:.2f}".format(round(price * x, 2)), sizes))
        return list(out)

    @property
    def order_size(self):
        return sum(list(Customer.objects.filter(order=self.pk).values_list('size', flat=True)))

    @property
    def discount(self):
        return self.product.discounts.discounts.get_percent(self.order_size)


class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    size = models.IntegerField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    objects = CustomerManager()

    def __str__(self):
        return f'{self.user} {self.size}'


class Manufacture(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Contributor(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Discount(models.Model):
    percent = models.IntegerField()
    size = models.IntegerField()
    objects = DiscountsManager()

    def __str__(self):
        return f'{self.percent}%{self.size}'


class DiscountSet(models.Model):
    discounts = models.ManyToManyField(Discount)

    def __str__(self):
        def frmt(discount):
            _, percent, size = discount
            return f'{percent}%{size}|'
        text = ''.join([x for x in map(frmt, self.discounts.values_list())])
        return f'|{text}'


class Product(models.Model):
    code = models.IntegerField(null=True)
    inn = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=255, null=True)
    manufacture = models.ForeignKey(Manufacture, on_delete=models.CASCADE)
    contributor = models.ForeignKey(Contributor, on_delete=models.CASCADE)
    ppv = models.IntegerField(default=0)
    pph = models.IntegerField(default=0)
    discounts = models.ForeignKey(DiscountSet, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} |{self.ppv}|{self.pph}{self.discounts}:{self.contributor}]'

    @property
    def prices(self):
        percent = self.discounts.discounts.get_all_percent()
        vals = self.discounts.discounts.get_values()
        # return map(lambda p: (p, self.pph - (self.pph/100) * p), percent)
        return map(lambda p: (p[0], p[1], "{:.2f}".format(self.pph - (self.pph/100) * p[0])), list(vals))

src/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField('email address')
    phone = models.CharField(max_length=16, null=True)
    location = models.CharField(max_length=16, default='')

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.username

src/orders/forms.py
from datetime import datetime

from django.forms import ModelForm, DateTimeField, ModelChoiceField, IntegerField, widgets, Form
from .models import Order, Product

DATETIME_FORMAT = "%Y-%m-%dT%H:%M"


class OrderCreationForm(ModelForm):
    date_finish = DateTimeField(
        label='Finish order',
        widget=widgets.DateTimeInput(
            attrs={"type": "datetime-local", "value": lambda: datetime.now().strftime(DATETIME_FORMAT)}
        ),
        localize=True,
        required=False,
    )
    size = IntegerField()

    class Meta:
        model = Order
        fields = ('date_finish', 'size', 'comment')


class AddSizeForm(Form):
    size = IntegerField()

src/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'phone', 'email', 'location')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'phone', 'email', 'location')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].help_text = None

src/orders/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import OrderCreationForm, AddSizeForm
from .models import Product, Order, Customer


class MyOrder(View):
    def get(self, req):
        orders = Order.objects.filter(creator=req.user)
        join_orders = Customer.objects.filter(user=req.user)
        return render(req, 'order/user.html', {'orders': orders, 'join_orders': [o.order for o in join_orders]})


class ListOrder(View):
    def get(self, req):
        orders = Order.objects.all()
        products = Product.objects.all()
        return render(req, 'order/order.html', {'orders': orders, 'products': products})


class CreateOrder(View):
    template = 'order/create.html'

    def get(self, req, pk):
        form = OrderCreationForm()
        return render(req, self.template, {'form': form})

    def post(self, req, pk):
        form = OrderCreationForm(req.POST)
        if not form.is_valid():
            return render(req, self.template, {'form': form})
        order = Order(product=Product.objects.get(pk=pk),
                      creator=req.user,
                      status='WORK',
                      date_finish=form.cleaned_data['date_finish'],
                      comment=form.cleaned_data['comment'])
        order.save()
        Customer(user=req.user, order=order, size=form.cleaned_data['size']).save()
        return redirect('order:detail', order.id)


class ShowOrder(View):
    def get(self, req, pk):

        def price_patch(prc, customers):
            def add_value(customer):
                customer.value = customer.size * prc
                return customer
            return [add_value(customer) for customer in customers]

        order = Order.objects.get(pk=pk)
        bayers = Customer.objects.filter(order=order)
        order_size = Customer.objects.get_order_size(order)
        percent = order.product.discounts.discounts.get_percent(order_size)
        percent_next, size_next = order.product.discounts.discounts.get_percent_next(percent)
        price = order.product.pph - (order.product.pph / 100) * percent
        context = {'bayers': price_patch(price, bayers),
                   'order': order,
                   'az': order_size,
                   'p': percent,
                   'price': "{:.2f}".format(price),
                   'percent': percent_next,
                   'add': size_next - order_size}
        return render(req, 'order/detail.html', context)


class ChangeOrderStatus(View):
    def get(self, req, pk, status):
        Order.objects.update_status(pk, status.upper())
        return redirect('order:list')


class DeleteOrder(View):
    def get(self, req, pk):
        Order.objects.get(pk=pk).delete()
        return redirect('order:list')


class AddCustomer(View):
    template = 'order/append.html'

    def get(self, req, pk):
        form = AddSizeForm()
        return render(req, self.template, {'form': form})

    def post(self, req, pk):
        form = AddSizeForm(req.POST)
        if not form.is_valid():
            return render(req, self.template, {'form': form})
        form.cleaned_data['user'] = req.user
        form.cleaned_data['order'] = Order.objects.get(pk=pk)
        if Customer.objects.filter(order=pk, user=req.user):
            customer = Customer.objects.get(order=pk, user=req.user)
            customer.size = customer.size + form.cleaned_data['size']
        else:
            customer = Customer(**form.cleaned_data)
        customer.save()
        return redirect('order:detail', pk)


class ChangeCustomer(View):
    template = 'order/change.html'

    def get(self, req, pk, ck):
        form = AddSizeForm(initial={'size': Customer.objects.get(pk=ck).size})
        return render(req, self.template, {'form': form})

    def post(self, req, pk, ck):
        form = AddSizeForm(req.POST)
        if not form.is_valid():
            return render(req, self.template, {'form': form})
        Customer.objects.set_size(ck, form.cleaned_data['size'])
        return redirect('order:detail', pk)


class DropCustomer(View):
    def get(self, req, pk, ck):
        Customer.objects.get(pk=ck).delete()
        return redirect('order:detail', pk)

src/users/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from .forms import CustomUserCreationForm, CustomUserChangeForm

User = get_user_model()


class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class ChangeUser(generic.UpdateView):
    model = User
    form_class = CustomUserChangeForm
    success_url = reverse_lazy('order:list')
    template_name = 'registration/change.html'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, pk=self.request.user.pk)

src/templates/order/append.html
{% extends 'base.html' %}

{% block title %}Add Size::{% endblock %}

{% block content %}

<div class="container mt-2 mb-5">
    <nav class="nav d-flex justify-content-between w-100 ">
        <h5>User: {{ request.user }}</h5>
        <div>
            <a class="btn btn-info ml-2" href="/orders/">MAIN</a>
            <a class="btn btn-info ml-2" href="{% url 'order:user' %}">MY ORDERS</a>
            <a class="btn btn-info ml-2" href="{% url 'user:change' %}">PROFILE</a>
            <a class="btn btn-outline-info ml-2" href="{% url 'logout' %}">LOG OUT</a>
        </div>
    </nav>
</div>
    <div class="vertical">
        <div class="container">
            <div class="center">
                <h2>Add size</h2>
                <form method='post'>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br>
                    <a class="btn btn-info" href="{% url 'order:list' %}">BACK</a>
                    <a href="" class="btn btn-info" onclick='this.parentNode.submit(); return false'>ADD</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/order/change.html
{% extends 'base.html' %}

{% block title %}Add Size::{% endblock %}

{% block content %}

<div class="container mt-2 mb-5">
    <nav class="nav d-flex justify-content-between w-100 ">
        <h5>User: {{ request.user }}</h5>
        <div>
            <a class="btn btn-info ml-2" href="/orders/">MAIN</a>
            <a class="btn btn-info ml-2" href="{% url 'order:user' %}">MY ORDERS</a>
            <a class="btn btn-info ml-2" href="{% url 'user:change' %}">PROFILE</a>
            <a class="btn btn-outline-info ml-2" href="{% url 'logout' %}">LOG OUT</a>
        </div>
    </nav>
</div>
    <div class="vertical">
        <div class="container">
            <div class="center">
                <h2>Change size</h2>
                <form method='post'>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br>
                    <a class="btn btn-info" href="{% url 'order:list' %}">BACK</a>
                    <a href="" class="btn btn-info" onclick='this.parentNode.submit(); return false'>CHANGE</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/order/create.html
{% extends 'base.html' %}

{% block title %}Create{% endblock %}

{% block content %}

<div class="container mt-2 mb-5">
    <nav class="nav d-flex justify-content-between w-100 ">
        <h5>User: {{ request.user }}</h5>
        <div>
            <a class="btn btn-info ml-2" href="/orders/">MAIN</a>
            <a class="btn btn-info ml-2" href="{% url 'order:user' %}">MY ORDERS</a>
            <a class="btn btn-info ml-2" href="{% url 'user:change' %}">PROFILE</a>
            <a class="btn btn-outline-info ml-2" href="{% url 'logout' %}">LOG OUT</a>
        </div>
    </nav>
</div>
    <div class="vertical">
        <div class="container">
            <div class="center">
                <h2>Create order</h2>
                <form method='post'>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br>
                    <a href="" class="btn btn-info" onclick='this.parentNode.submit(); return false;'>CREATE</a>
                    <a class="btn btn-info" href="{% url 'order:list' %}">BACK</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/order/detail.html
{% extends 'base.html' %}

{% block title %}Order{% endblock %}

{% block content %}
<div class="container mt-2 mb-5">
    <nav class="nav d-flex justify-content-between w-100 ">
        <h5>User: {{ request.user }}</h5>
        <div>
            <a class="btn btn-info ml-2" href="/orders/">MAIN</a>
            <a class="btn btn-info ml-2" href="{% url 'order:user' %}">MY ORDERS</a>
            <a class="btn btn-info ml-2" href="{% url 'user:change' %}">PROFILE</a>
            <a class="btn btn-outline-info ml-2" href="{% url 'logout' %}">LOG OUT</a>
        </div>
    </nav>
</div>
<div class="container">
    <div class="center">
        <h1>Order</h1>
        <table class="table table-striped mb-3">
            <tbody>
            <tr>
                <td class="text-left"> Creator:</td>
                <td class="text-left"> {{ order.creator }}</td>
            </tr>
            <tr>
                <td class="text-left"> Product:</td>
                <td class="text-left"> {{ order.product.name }}</td>
            </tr>
            <tr>
                <td class="text-left"> Address:</td>
                <td class="text-left">{{ order.creator.location }}</td>
            </tr>
            <tr>
                <td class="text-left"> Status:</td>
                <td class="text-left">{{ order.status }}</td>
            </tr>
            <tr>
                <td class="text-left"> Start date:</td>
                <td class="text-left"> {{ order.date_start }}</td>
            </tr>
            <tr>
                <td class="text-left"> Finish date:</td>
                <td class="text-left">{{ order.date_finish }}</td>
            </tr>
            <!--            <tr> <td class="text-left"> PPV: {{ order.product.ppv }} </p>-->
            <!--            <tr> <td class="text-left"> PPH: {{ order.product.pph }} </p>-->
            <tr>
                <td class="text-left"> Discounts:</td>
                <td class="text-left"> {{ order.product.discounts }}</td>
            </tr>
            <tr>
                <td class="text-left"> Comment:</td>
                <td class="text-left">{{ order.comment }}</td>
            </tr>
            </tbody>
        </table>

        <table class="table table-striped mb-5 pb-5">
            <tbody>
            <tr>
                <td class="text-left"> Lot in order:</td>
                <td class="text-left">{{ az }}</td>
            </tr>
            <tr>
                <td class="text-left"> PF {{ p }}%</td>
                <td class="text-left">{{ price }}</td>
            </tr>
            <tr>
                <td class="text-left"> Next discount:</td>
                <td class="text-left">{{ percent }}%</td>
            </tr>
            <tr>
                <td class="text-left"> Need add to get next discount:</td>
                <td class="text-left"> {{ add }}</td>
            </tr>

            </tbody>
        </table>

        <h5 class="mb-2 text-left">Customer list</h5>
        <table class="mb-4">
            <tr>
                <th>Customer</th>
                <th>Size</th>
                <th>Price</th>
                <th>Delete</th>
                <th>Change</th>
            </tr>
            {% for bayer in bayers %}
            <tr>
                <td> {{ bayer.user }}</td>
                <td> {{ bayer.size }}</td>
                <td> {{ bayer.value }}</td>
                <td>
                    {% if request.user == bayer.user and order.status == 'WORK' %}
                    <a class="btn btn-outline-danger" href="{% url 'order:drop' order.pk bayer.pk %}">Del</a>
                    {% endif %}
                </td>
                <td>
                    {% if request.user == bayer.user and order.status == 'WORK' %}
                    <a class="btn btn-outline-success" href="{% url 'order:update' order.pk bayer.pk %}">Change</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        <a class="btn btn-info mb-5" href="{% url 'order:list' %}">BACK</a>
    </div>
</div>
{% endblock %}

src/templates/order/order.html
{% extends 'base.html' %}

{% block title %}Order{% endblock %}

{% block content %}
<div class="container">
    <div class="center">
    </div>
</div>
<div class="container mt-2 mb-5">
    <nav class="nav d-flex justify-content-between w-100 ">
        <h5>User: {{ request.user }}</h5>
        <div>
            <a class="btn btn-info ml-2" href="{% url 'order:user' %}">MY ORDERS</a>
            <a class="btn btn-info ml-2" href="{% url 'user:change' %}">PROFILE</a>
            <a class="btn btn-outline-info ml-2" href="{% url 'logout' %}">LOG OUT</a>
        </div>
    </nav>
</div>
<div class="form-inline my-2 my-lg-0 mt-5 mb-5 container pt-5 flex-column">
    <h4 class="mb-1"> Global search !</h4>
    <div>
        <input id="searchWord" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <div id="searchGo" class="btn btn-outline-success my-2 my-sm-0">Search</div>

    </div>
</div>
<div class="container mb-5 mt-5 flex-column">
    <h4 class="mb-1"> ORDERS IN WORK: </h4>
    <div class="scroll min-h-440">
        <div class="tableFixHead min-h-440">
            <table class="table table-striped min-h-440">
                <thead>
                <tr>
                    <th>Join</th>
                    <th>Detail</th>
                    <th>Creator</th>
                    <th>Product</th>
                    <th>Manufacture</th>
                    <th>Size</th>
                    <th>Now</th>
                    <th>Customers
                        <!--                        <table class="table table-sm">-->
                        <!--                            <tr class="d-flex flex-column">-->
                        <!--                                <th class="table-primary">Name</th>-->
                        <!--                                <th class="table-success">Size</th>-->
                        <!--                                <th class="table-warning">Price</th>-->
                        <!--                            </tr>-->
                        <!--                        </table>-->

                    </th>
                    <th>Date</th>
                    <th>Location</th>
                </tr>
                </thead>
                {% for order in orders %}
                {% if order.status == 'WORK' %}


                <tr>
                    <td class="align-middle"><a class="btn btn-info" href="{% url 'order:append' order.id %}">Join</a></td>
                    <td class="align-middle"><a class="btn btn-outline-info" href="{% url 'order:detail' order.id %}">Detail</a></td>
                    <td class="align-middle"> {{ order.creator }}</td>
                    <td class="align-middle searchInMe"> {{ order.product.name }}</td>
                    <td class="align-middle"> {{ order.product.manufacture }}</td>
                    <td class="align-middle"> {{ order.order_size }}</td>
                    <td class="align-middle"> {{ order.discount }}%</td>
                    <td class="align-middle">
                        {% for customer in order.customers %}
                        <table class="table table-sm border-dark">
                            <tr class="d-flex flex-column">
                                <td class="table-primary">
                                    Name: {{ customer.0 }}
                                </td>
                                <td class="table-success">
                                    Size: {{ customer.1 }}
                                </td>
                                <td class="table-warning">
                                    Price: {{ customer.2 }}
                                </td>
                            </tr>
                        </table>
                        {% endfor %}
                    </td>
                    <td class="align-middle"> {{ order.date_finish }}</td>
                    <td class="align-middle"> {{ order.creator.location }}</td>
                </tr>
                {% endif %}
                {% endfor %}
            </table>
        </div>
    </div>
</div>
<div class="container mb-5 mt-5 flex-column">
    <h4 class="mb-1">CAN BE ORDERED: </h4>
    <div class="scroll">
        <div class="tableFixHead">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Create</th>
                    <th>Code</th>
                    <th>Name</th>
                    <!--                    <th>NMM</th>-->
                    <!--                    <th>PPV</th>-->
                    <!--                    <th>PPH</th>-->
                    <th>{{ p1 }}% / RF</th>
                    <th>{{ p1 }}% / RF</th>
                    <th>{{ p1 }}% / RF</th>
                    <th>{{ p1 }}% / RF</th>
                </tr>
                </thead>
                {% for product in products %}
                <tr>
                    <td class="align-middle"><a class="btn btn-outline-info" href="{% url 'order:create' product.pk %}">Order</a></td>
                    <td class="align-middle searchInMe"> {{ product.code }}</td>
                    <td class="align-middle searchInMe"> {{ product.name }}</td>
                    <!--                        <td class="align-middle searchInMe" "> {{ product.nmm }}</td>-->
                    <!--                        <td class="align-middle" "> {{ product.ppv }}</td>-->
                    <!--                        <td class="align-middle" "> {{ product.pph }}</td>-->
                    {% for price in product.prices %}
                    <td class="align-middle"> {{ price.1 }} / {{ price.2 }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>


{% endblock %}

src/templates/order/user.html
{% extends 'base.html' %}

{% block title %}My Order{% endblock %}

{% block content %}

<div class="container">
    <div class="center">
        <!--            <p>-->
        <!--                User: {{ request.user }}-->
        <!--                <a class="btn btn-info" href="{% url 'logout' %}">LOG OUT</a>-->
        <!--            </p>-->
        <div class="container mt-2 mb-5">
            <nav class="nav d-flex justify-content-between w-100 ">
                <h5>User: {{ request.user }}</h5>
                <div>
                    <a class="btn btn-info ml-2" href="/orders/">MAIN</a>
                    <a class="btn btn-info ml-2" href="{% url 'user:change' %}">PROFILE</a>
                    <a class="btn btn-outline-info ml-2" href="{% url 'logout' %}">LOG OUT</a>
                </div>
            </nav>
        </div>
        <p> MY ORDERS: </p>
        <div class="tableFixHead">
            <table>
                <thead>

                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>Product</th>
                    <th>Customers</th>
                    <th>Manufacture</th>
                    <th>Contributor</th>
                    <th>Size</th>
                    <th>Now</th>
                    <th>Discounts</th>
                </tr>
                </thead>
                {% for order in orders %}
                <tr>
                    <td><a class="btn btn-info" href="{% url 'order:detail' order.id %}">DETAIL</a></td>
                    <td>
                        {% if request.user == order.creator %}
                        <a class="btn btn-info" href="{% url 'order:delete' order.id %}">DELETE</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if request.user == order.creator and order.status == 'WORK' %}
                        <a class="btn btn-info" href="{% url 'order:status' order.id 'archive' %}">IN ARCHIVE</a>
                        {% endif %}
                        {% if request.user == order.creator and order.status == 'ARCHIVE' %}
                        <a class="btn btn-info" href="{% url 'order:status' order.id 'work' %}">IN WORK</a>
                        {% endif %}
                    </td>
                    <td> {{ order.product.name }}</td>
                    <td> {{ order.customers }}</td>
                    <td> {{ order.product.manufacture.name }}</td>
                    <td> {{ order.product.contributor.name }}</td>
                    <td> {{ order.order_size }}</td>
                    <td> {{ order.discount }}%</td>
                    <td> {{ order.product.discounts }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <p> ORDERS WITH ME: </p>
        <div class="tableFixHead">
            <table>
                <thead>

                <tr>
                    <th></th>
                    <th>Product</th>
                    <th>Customers</th>
                    <th>Manufacture</th>
                    <th>Contributor</th>
                    <th>Size</th>
                    <th>Now</th>
                    <th>Discounts</th>
                </tr>
                </thead>
                {% for order in join_orders %}
                <tr>
                    <td><a class="btn btn-info" href="{% url 'order:detail' order.id %}">DETAIL</a></td>
                    <td> {{ order.product.name }}</td>
                    <td> {{ order.customers }}</td>
                    <td> {{ order.product.manufacture.name }}</td>
                    <td> {{ order.product.contributor.name }}</td>
                    <td> {{ order.order_size }}</td>
                    <td> {{ order.discount }}%</td>
                    <td> {{ order.product.discounts }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
<a class="btn btn-info mb-5 mt-5 ml-auto mr-auto" href="{% url 'order:list' %}">BACK</a>

{% endblock %}